# Use emacs keymap as the default.
bindkey -e

# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git colored-man-pages arduino-cli)

ZSH_THEME=sorin
source $ZSH/oh-my-zsh.sh

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="1000"
SAVEHIST="1000"

HISTFILE="/home/cocotreb/.histfile"
mkdir -p "$(dirname "$HISTFILE")"

# Set shell options
set_opts=(
  HIST_FCNTL_LOCK HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY
  NO_APPEND_HISTORY NO_EXTENDED_HISTORY NO_HIST_EXPIRE_DUPS_FIRST
  NO_HIST_FIND_NO_DUPS NO_HIST_IGNORE_ALL_DUPS NO_HIST_SAVE_NO_DUPS
)
for opt in "${set_opts[@]}"; do
  setopt "$opt"
done
unset opt set_opts

# Unset beep
unsetopt beep

# PATH
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH"

# Oh My Zsh update reminder
zstyle ':omz:update' mode reminder

HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"

alias -- homelabssh='ssh cocotreb@100.64.237.9'
alias -- listgens='sudo nix-env --list-generations --profile /nix/var/nix/profiles/system'
alias -- pwdcp='pwd | wl-copy && echo '\''current directory copied'\'''
alias -- switchgen='sudo nix-env --switch-generation --profile /nix/var/nix/profiles/system'
alias -- wttr='curl wttr.in | less'
