# window rules
for_window [app_id="^.*"] inhibit_idle fullscreen
for_window [shell="xwayland"] title_format "%title (%shell)"

# floating mode windows
for_window [title="File Operation Progress"] floating enable
for_window [title="Confirm to replace files"] floating enable
for_window [title="Rename "] floating enable
for_window [title="Qalculate!"] floating enable
for_window [title="zoom"] floating enable
for_window [title="Choose a profile"] floating enable
for_window [title="Library"] floating enable
for_window [class="(?i)\.exe$"] floating enable
for_window [app_id="(?i)\.exe$"] floating enable
for_window [class="steam_app"] floating enable
for_window [app_id="steam_app"] floating enable
for_window [app_id="org.prismlauncher.PrismLauncher"] floating enable

